### ISSUE TITLE
ENOENT when opening preview window

### ISSUE THREAD

**Issue by pnorman** [stamen/CartoDB-basemaps#16]
When opening up Preview on `dark-matter-all.yml` I get the error `ENOENT: no such file or directory, open 'C:\work\cartodb\CartoDB-basemaps\layers.yml'`

It appears to be looking for `J:\work\cartodb\CartoDB-basemaps\layers.yml`, which does exist.

**Comment by sethfitz** [comment]
Weird! This actually sounds like an Atom bug where the drive isn't being included / respected for some reason.

https://github.com/stamen/atom-cartodb/blob/v0.7.3/lib/cartodb.js#L47-L49 seems to be doing the right thing.

Can you open up the developer console and post what `process.cwd()` returns when you have this project open?

**Comment by pnorman** [comment]
`"C:\Users\pnorman\AppData\Local\atom\app-1.4.0"`

**Comment by sethfitz** [comment]
How about:

``` javascript
atom.workspace.getActiveTextEditor().getPath() // with project.yml focused
path.dirname(atom.workspace.getActiveTextEditor().getPath())
```

How are you initiating Preview? Via right-click or command palette / menu? (The latter provides paths via event (https://github.com/stamen/atom-cartodb/blob/v0.7.3/index.js#L18))

**Comment by pnorman** [comment]
```
atom.workspace.getActiveTextEditor().getPath()
"J:\work\cartodb\CartoDB-basemaps\dark-matter.yml"

path.dirname(atom.workspace.getActiveTextEditor().getPath())
VM996:2 Uncaught ReferenceError: path is not defined(…)(anonymous function) @ VM996:2InjectedScript._evaluateOn @ VM839:904InjectedScript._evaluateAndWrap @ VM839:837InjectedScript.evaluate @ VM839:693
```

> Via right-click or command palette / menu?

When in atom, command palette, search for carto, click on it

**Comment by sethfitz** [comment]
Err, sorry:

``` javascript
var path = require("path");
path.dirname(atom.workspace.getActiveTextEditor().getPath())
```
